name: publish_conda

on:
  release:
    types: [published]
    
jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git

    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: fcakyon/conda-publish-action@v1.3
      with:
        subdir: 'conda-build'
        anacondatoken: ${{ secrets.CONDAAPITOKEN }}
        platforms: 'win osx linux'